apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-d
  template:
    metadata:
      labels:
        app: service-d
    spec:
      containers:
        - name: service-d-container
          image: hardvan/flask-service-d:latest
          ports:
            - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: service-d
spec:
  selector:
    app: service-d
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
